const players=[
{name:'Elyas R.',pos:'ATT',age:19,value:8.5,pot:86,pace:91,tech:84,club:'Lorient'},
{name:'Mathis K.',pos:'MIL',age:20,value:11,pot:84,pace:78,tech:88,club:'Nantes'},
{name:'Ibrahim S.',pos:'ATT',age:18,value:5.5,pot:88,pace:94,tech:80,club:'Metz'},
{name:'Lucas M.',pos:'DEF',age:21,value:7,pot:82,pace:76,tech:79,club:'Troyes'},
{name:'Noah B.',pos:'MIL',age:19,value:9,pot:87,pace:85,tech:91,club:'Reims'},
{name:'Yanis D.',pos:'DEF',age:20,value:4.5,pot:83,pace:88,tech:77,club:'Caen'},
{name:'Sacha T.',pos:'ATT',age:21,value:13,pot:85,pace:89,tech:87,club:'Rennes'},
{name:'Milan A.',pos:'MIL',age:18,value:3.8,pot:90,pace:82,tech:89,club:'Auxerre'}];

function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');window.scrollTo(0,0)}
function calc(){let b=+budget.value,v=+value.value,r=+rep.value,u=+urgency.value;let adjusted=v*r*u;let initial=Math.min(b,adjusted*.88),max=Math.min(b,adjusted*1.12);offer.innerHTML=`<b>💰 Offre FM26+</b><br>Valeur ajustée : <strong>${adjusted.toFixed(1)} M€</strong><br>Offre initiale : <strong>${initial.toFixed(1)} M€</strong><br>Maximum conseillé : <strong>${max.toFixed(1)} M€</strong><br><br>💡 Garde au moins 10% de ton budget pour les imprévus.`}
function filterPlayers(){let q=(searchPlayer.value||'').toLowerCase(),pos=posFilter.value,age=+ageMax.value||40,pot=+potMin.value||0,val=+valueMax.value||999;let list=players.filter(p=>(!q||p.name.toLowerCase().includes(q))&&(pos==='all'||p.pos===pos)&&p.age<=age&&p.pot>=pot&&p.value<=val);playersDiv.innerHTML=list.map(p=>`<div class="player"><div><b>${p.name}</b><br><small>${p.pos} · ${p.age} ans · ${p.value} M€ · ${p.club}</small><br><small>VIT ${p.pace} · TEC ${p.tech}</small></div><div class="rating">POT ${p.pot}</div></div>`).join('')||'<div class="result">Aucun joueur ne correspond.</div>'}
function comparePlayers(){let a=players.find(p=>p.name===p1.value),b=players.find(p=>p.name===p2.value);if(!a||!b)return;let winner=a.pot>b.pot?a:b;compare.innerHTML=`<b>⚔️ ${a.name} vs ${b.name}</b><br><br>Potentiel : <strong>${a.pot}</strong> — <strong>${b.pot}</strong><br>Vitesse : ${a.pace} — ${b.pace}<br>Technique : ${a.tech} — ${b.tech}<br>Valeur : ${a.value} M€ — ${b.value} M€<br><br>🏆 Profil le plus intéressant à long terme : <strong>${winner.name}</strong>`}
function analyzeSquad(){squadResult.innerHTML=`<b>📊 Diagnostic</b><br><br>🔴 <strong>Priorité 1 :</strong> renforcer la charnière centrale.<br>🟠 <strong>Priorité 2 :</strong> ajouter un milieu capable de casser les lignes.<br>🟢 <strong>Point fort :</strong> vitesse et potentiel offensif.<br><br><b>Plan conseillé :</b> 1 défenseur titulaire + 1 jeune milieu à fort potentiel.`}
function coach(){let p=problem.value.toLowerCase();let advice=p.includes('4-3-3')?'Passe en 4-2-3-1, ferme les demi-espaces et attaque rapidement derrière leurs latéraux.':p.includes('plus forte')?'Bloc médian compact, transitions rapides et peu de risques dans la première relance.':'Adapte seulement 2 ou 3 consignes clés : hauteur du bloc, pressing et zones d’attaque.';document.getElementById('coach').innerHTML=`<b>🧠 Analyse FM26+</b><br>${advice}<br><br>🎯 <b>Priorité :</b> conserve une structure stable et exploite la faiblesse principale de l’adversaire.`}
const playersDiv=document.getElementById('players');const p1=document.getElementById('p1'),p2=document.getElementById('p2');players.forEach(p=>{p1.add(new Option(p.name,p.name));p2.add(new Option(p.name,p.name))});p2.selectedIndex=1;filterPlayers();comparePlayers();
